### ISSUE TITLE
Strange Compile Error

### ISSUE THREAD

**Issue by CaptainBaldi** [MAJigsaw77/hxdiscord_rpc#3]
When using the latest release of the library, I get an error message when I try to compile.
![image](https://github.com/MAJigsaw77/hxdiscord_rpc/assets/86160807/7d1bac13-0b7c-4100-a99f-be4c70755007)
This code worked fine previously however it seems to not work, although no significant changes have been made to the source.
A pastebin with my code can be viewed [here](https://pastebin.com/2vuC88tj), although it's basically just the example in samples, with a few small changes

**Comment by MAJigsaw77** [comment]
On the line 25 in your code you should add DiscordRichPresence.create();, mostly these are issues from hxcpp, not from the library itself really.

**Comment by CaptainBaldi** [comment]
I tweaked the code a little bit, and that seemed to fix the issue, so ig I'll close this.

**Comment by MAJigsaw77** [comment]
> I tweaked the code a little bit, and that seemed to fix the issue, so ig I'll close this.

Sometimes hxcpp can do weird stuff and that's kinda it.
