### ISSUE TITLE
?

### ISSUE THREAD

**Issue by 2JENO** [MAJigsaw77/hxdiscord_rpc#4]
Assertion failed: bytesToRead == bytesRead, file C:/HaxeToolkit/haxe/lib/hxdiscord_rpc/git/project/discord-rpc/src/connection_win.cpp, line 116

**Comment by MAJigsaw77** [comment]
This issue is related to discord rpc itself but it might be that the function are updated too frequently.

**Comment by 2JENO** [comment]
> This issue is related to discord rpc itself but it might be that the function are updated too frequently.

but still crash anytime

**Comment by MAJigsaw77** [comment]
> > This issue is related to discord rpc itself but it might be that the function are updated too frequently.
> 
> but still crash anytime

Assuming that yo

**Comment by MAJigsaw77** [comment]
So the functions will not update that frequency anymore.

**Comment by 2JENO** [comment]
> > > This issue is related to discord rpc itself but it might be that the function are updated too frequently.
> > 
> > but still crash anytime
> 
> Assuming that you are using the sample, replace `Sys.sleep(0.5);` to `Sys.sleep(2);`.

hmm im from fnf psych engine, and i never see Sys.sleep code

**Comment by MAJigsaw77** [comment]
> > > > This issue is related to discord rpc itself but it might be that the function are updated too frequently.
> > > 
> > > 
> > > but still crash anytime
> > 
> > 
> > Assuming that you are using the sample, replace `Sys.sleep(0.5);` to `Sys.sleep(2);`.
> 
> hmm im from fnf psych engine, and i never see Sys.sleep code

https://github.com/ShadowMario/FNF-PsychEngine/blob/d64912e57120e27dc41304deae48097b6c1355d1/source/backend/Discord.hx#L76

**Comment by 2JENO** [comment]
oh sorry lol

**Comment by 2JENO** [comment]
still crash,,,
